version: '2'
services:
  nodejs:
    container_name: nodejs
    image: nodejs
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: always
